Repository zeta-middleware/zeta, pull requests merged in 2020-05, with the labels that each got.

#41 Add service code generation option to the zeta-cli
  zeta/_version.py
  zeta/templates/zeta_service.template.c
  zeta/zeta.py
Labels: feature

#42 Change the focus of the pub sub to service
  samples/basic/zeta.yaml
  samples/light_control/prj.conf
  samples/light_control/src/net.c
  samples/light_control/zeta.yaml
  tests/zeta.yaml
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/templates/zeta.template.yaml
  zeta/templates/zeta_callbacks.template.h
  zeta/templates/zeta_custom_functions.template.h
  zeta/templates/zeta_threads.template.c
  zeta/templates/zeta_threads.template.h
  zeta/zeta.py
Labels: enhancement

#49 Improve output colors and text
  zeta/zeta.py
Labels: enhancement

#48 Feature/service abstraction c code
  samples/basic/src/main.c
  samples/basic/zeta.yaml
  samples/light_control/src/core.c
  samples/light_control/src/net.c
  samples/light_control/src/peripheral.c
  tests/src/test_functions.c
  tests/src/test_main.c
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/templates/zeta/CMakeLists.txt
  zeta/templates/zeta_services.template.h
  zeta/templates/zeta_threads.template.c
  zeta/zeta.py
Labels: feature

#51 Enhancement/templates
  samples/basic/src/main.c
  samples/light_control/src/core.c
  samples/light_control/src/net.c
  samples/light_control/src/peripheral.c
  tests/src/test_functions.c
  tests/src/test_main.c
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/templates/zeta.template.yaml
  zeta/templates/zeta_callbacks.template.h
  zeta/templates/zeta_service.template_c
  zeta/templates/zeta_services.template.h
  zeta/templates/zeta_with_services.template.cmake
  zeta/zeta.py
Labels: enhancement

#57 Enhancement/set to publish
  samples/basic/src/main.c
  samples/basic/zeta.yaml
  samples/light_control/CMakeLists.txt
  samples/light_control/src/core.c
  samples/light_control/src/net.c
  samples/light_control/src/peripheral.c
  samples/light_control/zeta.yaml
  tests/src/test_functions.c
  tests/zeta.yaml
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/templates/zeta.template.yaml
  zeta/zeta.py
Labels: enhancement

#60 Add project template
  samples/template_project/CMakeLists.txt
  samples/template_project/prj.conf
Labels: enhancement

#61 Enhancement/fix name functions
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/zeta.py
Labels: enhancement

#65 Bug/modules
  zeta/templates/zeta.template.cmake
Labels: bug

#66 Fix zeta services command generation
  zeta/templates/zeta_with_services.template.cmake
Labels: bug

#67 Enhancement/add callback behavior
  tests/src/test_functions.c
  tests/src/test_main.c
  tests/zeta.yaml
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/zeta.py
Labels: enhancement

#68 Enhancement/change zt channel read publish name
  samples/basic/src/main.c
  samples/light_control/src/core.c
  samples/light_control/src/net.c
  samples/light_control/src/peripheral.c
  tests/src/test_functions.c
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/zeta.py
Labels: enhancement

#69 Article/create example to experimental evaluation
  samples/sensors-over-internet/CMakeLists.txt
  samples/sensors-over-internet/prj.conf
  samples/sensors-over-internet/src/board.c
  samples/sensors-over-internet/src/core.c
  samples/sensors-over-internet/src/net.c
  samples/sensors-over-internet/zeta.cmake
  samples/sensors-over-internet/zeta.yaml
  tests/src/test_functions.c
  zeta/zeta.py
Labels: samples

#71 Enhancement/change priorities and add storage sleep time config to yaml
  samples/basic/zeta.yaml
  samples/light_control/zeta.yaml
  samples/sensors-over-internet/zeta.yaml
  tests/zeta.yaml
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/templates/zeta.template.yaml
  zeta/zeta.py
Labels: enhancement

#73 Add release candidate version 0.2.0rc1
  pip_cli
  version.yaml
  zeta/_version.py
Labels: enhancement

#82 Fix zeta check command and improve output
  .gitignore
  zeta/zeta.py
Labels: bug, cli

#83 Add persistency to sensors over internet sample code
  samples/sensors-over-internet/src/board.c
  samples/sensors-over-internet/src/net.c
  samples/sensors-over-internet/zeta.yaml
Labels: samples

#84 Enhancement/strings
  zeta/zeta.py
Labels: cli, enhancement

#86 Samples/pub cb
  samples/pub_cb_o2n_performance/CMakeLists.txt
  samples/pub_cb_o2n_performance/Kconfig
  samples/pub_cb_o2n_performance/README.txt
  samples/pub_cb_o2n_performance/channel_latency_o2n.png
  samples/pub_cb_o2n_performance/chart.py
  samples/pub_cb_o2n_performance/nrf52840_pca10059.conf
  samples/pub_cb_o2n_performance/prj.conf
  samples/pub_cb_o2n_performance/src/ping.c
  samples/pub_cb_o2n_performance/src/pong.c
  samples/pub_cb_o2n_performance/src/s02.c
  samples/pub_cb_o2n_performance/src/s03.c
  samples/pub_cb_o2n_performance/src/s04.c
  samples/pub_cb_o2n_performance/src/s05.c
  samples/pub_cb_o2n_performance/src/s06.c
  samples/pub_cb_o2n_performance/src/s07.c
  samples/pub_cb_o2n_performance/src/s08.c
  samples/pub_cb_o2n_performance/src/s09.c
  samples/pub_cb_o2n_performance/src/s10.c
  samples/pub_cb_o2n_performance/zeta.cmake
  samples/pub_cb_o2n_performance/zeta.yaml
  samples/pub_cb_o2o_performance/CMakeLists.txt
  samples/pub_cb_o2o_performance/Kconfig
  samples/pub_cb_o2o_performance/README.txt
  samples/pub_cb_o2o_performance/channel_latency.png
  samples/pub_cb_o2o_performance/chart.py
  samples/pub_cb_o2o_performance/nrf52840_pca10059.conf
  samples/pub_cb_o2o_performance/prj.conf
  samples/pub_cb_o2o_performance/src/ping.c
  samples/pub_cb_o2o_performance/src/pong.c
  samples/pub_cb_o2o_performance/zeta.cmake
  samples/pub_cb_o2o_performance/zeta.yaml
Labels: mid, samples

#88 Enhancement/port
  Dockerfile
  samples/basic/CMakeLists.txt
  samples/basic/zeta.cmake
  samples/light_control/CMakeLists.txt
  samples/light_control/zeta.cmake
  samples/pub_cb_o2n_performance/CMakeLists.txt
  samples/pub_cb_o2n_performance/Kconfig
  samples/pub_cb_o2n_performance/channel_latency_o2n.png
  samples/pub_cb_o2n_performance/chart.py
  samples/pub_cb_o2n_performance/prj_nrf52840_pca10059.conf
  samples/pub_cb_o2n_performance/src/ping.c
  samples/pub_cb_o2o_performance/CMakeLists.txt
  samples/pub_cb_o2o_performance/Kconfig
  samples/pub_cb_o2o_performance/channel_latency.png
  samples/pub_cb_o2o_performance/chart.py
  samples/pub_cb_o2o_performance/prj_nrf52840_pca10059.conf
  samples/pub_cb_o2o_performance/src/ping.c
  samples/sensors-over-internet/CMakeLists.txt
  samples/sensors-over-internet/zeta.cmake
  samples/template_project/CMakeLists.txt
  tests/CMakeLists.txt
  tests/zeta.cmake
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
Labels: enhancement, mid

#90 Samples/profiler
  Dockerfile
  samples/sensors-over-internet/data/metadata
  samples/sensors-over-internet/prj.conf
  samples/sensors-over-internet/prj_nrf52840_pca10059.conf
  samples/sensors-over-internet/src/net.c
  samples/sensors-over-internet/trace.py
  zeta/templates/zeta.template.c
  zeta/templates/zeta/Kconfig
Labels: enhancement, mid, samples

#92 Enhancement/performance
  samples/basic/src/main.c
  samples/basic/zeta.yaml
  samples/light_control/src/net.c
  samples/light_control/zeta.yaml
  samples/pub_cb_o2n_performance/zeta.yaml
  samples/pub_cb_o2o_performance/channel_latency.png
  samples/pub_cb_o2o_performance/chart.py
  samples/pub_cb_o2o_performance/zeta.yaml
  samples/sensors-over-internet/zeta.yaml
  tests/src/test_functions.c
  tests/src/test_main.c
  tests/zeta.yaml
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/zeta.py
Labels: enhancement, mid, refactoring

#94 DONE #78: Add type hints
  pip_cli
  zeta/zeta.py
Labels: cli, enhancement

#93 Documentation/add doxygen cli
  zeta/zeta.py
Labels: cli, documentation

#96 Add type hints to ZetaCLI
  pip_cli
Labels: cli, enhancement

#97 Merge branch 'documentation/add-doxygen-cli' into enhancement/add-typ…
  pip_cli
  zeta/zeta.py
Labels: cli, documentation

#99 Bug/zeta cli return err code
  samples/basic/zeta.cmake
  samples/light_control/zeta.cmake
  samples/pub_cb_o2n_performance/zeta.cmake
  samples/pub_cb_o2o_performance/zeta.cmake
  samples/sensors-over-internet/zeta.cmake
  tests/zeta.cmake
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta_with_services.template.cmake
  zeta/zeta.py
  zeta/zeta_errors.py
Labels: bug, cli

#102 Enhancement/flag remove storage
  samples/basic/prj.conf
  samples/basic/zeta.cmake
  samples/light_control/prj.conf
  samples/light_control/zeta.cmake
  samples/pub_cb_o2n_performance/prj.conf
  samples/pub_cb_o2n_performance/prj_nrf52840_pca10059.conf
  samples/pub_cb_o2n_performance/zeta.cmake
  samples/pub_cb_o2o_performance/prj.conf
  samples/pub_cb_o2o_performance/prj_nrf52840_pca10059.conf
  samples/pub_cb_o2o_performance/zeta.cmake
  samples/sensors-over-internet/prj.conf
  samples/sensors-over-internet/prj_nrf52840_pca10059.conf
  samples/sensors-over-internet/zeta.cmake
  samples/template_project/prj.conf
  tests/CMakeLists.txt
  tests/prj.conf
  tests/zeta.cmake
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta.template.conf
  zeta/templates/zeta/Kconfig
  zeta/templates/zeta_with_services.template.cmake
  zeta/zeta.py
Labels: cli, enhancement, mid

#103 Enhancement/config yaml optional
  zeta/zeta.py
Labels: cli, enhancement

#104 Release 0.2.0rc2
  pip_cli
  version.yaml
  zeta/_version.py
Labels: Release
