Repository zeta-middleware/zeta, pull requests merged in 2020-06, with the labels that each got.

#111 Bug/zeta init
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta.template.yaml
  zeta/templates/zeta_with_services.template.cmake
  zeta/zeta.py
Labels: bug, cli

#112 Bug/fix cli services checks
  zeta/zeta.py
Labels: bug, cli

#113 Enhancement/zeta cli tests
  .github/workflows/test-zeta.yml
  .gitignore
  Dockerfile
  action.yaml
  zeta-cli-tests
  zeta-mid-tests
  zeta-tests
  zeta/zeta.py
  zeta/zeta_errors.py
Labels: cli, enhancement

#115 Enhancement/zeta cli cmds output
  zeta/zeta.py
Labels: cli, enhancement

#117 Release version 0.2.0
  version.yaml
  zeta/_version.py
Labels: Release

#119 Release version 0.2.0
  .github/workflows/test-zeta.yml
  .gitignore
  Dockerfile
  action.yaml
  samples/light_control/src/main.c
  version.yaml
  zeta-cli-tests
  zeta-mid-tests
  zeta-sample-tests
  zeta-tests
  zeta-update-cli
  zeta/_version.py
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta.template.h
  zeta/templates/zeta.template.yaml
  zeta/templates/zeta_custom_functions.template.h
  zeta/templates/zeta_with_services.template.cmake
  zeta/zeta.py
  zeta/zeta_errors.py
Labels: Release

#125 Change NO_POLICE_SCOPE to NO_POLICY_SCOPE
  Dockerfile
  samples/pub_cb_o2n_performance/CMakeLists.txt
  samples/pub_cb_o2o_performance/CMakeLists.txt
Labels: bug, cli

#128 Feature/zeta forwarder
  samples/basic/prj.conf
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/templates/zeta/Kconfig
  zeta/zeta.py
Labels: cli, feature, mid
