Repository zeta-middleware/zeta, pull requests merged in 2020-04, with the labels that each got.

#3 Update the project structure
  CMakeLists.txt
  assets/docker/.env
  assets/docker/Dockerfile
  assets/docker/docker-compose.yml
  prj.conf
  samples/basic/CMakeLists.txt
  samples/basic/prj.conf
  samples/basic/src/main.c
  samples/basic/zeta.cmake
  samples/basic/zeta.conf
  samples/basic/zeta.yaml
  tests/CMakeLists.txt
  tests/include/zeta_unit_tests.h
  tests/prj.conf
  tests/src/test_functions.c
  tests/src/test_main.c
  tests/zeta.cmake
  tests/zeta.conf
  tests/zeta.yaml
Labels: enhancement

#7 Add Zephyr module compilation support
  MANIFEST.in
  setup.py
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta.template.conf
  zeta/templates/zeta/CMakeLists.txt
  zeta/templates/zeta/Kconfig
  zeta/templates/zeta/include/.empty
  zeta/templates/zeta/src/.empty
  zeta/zeta.py
Labels: enhancement

#8 Add zephyr module folder
  .gitignore
  zeta/templates/zeta/zephyr/module.yml
Labels: enhancement

#15 Enhancement/pip2
  pip_cli
  pip_upload
  setup.py
  zeta/__init__.py
  zeta/_version.py
  zeta/zeta.py
Labels: enhancement

#13 Develop
  .clang-format
  .gitignore
  CMakeLists.txt
  Dockerfile
  LICENSE
  MANIFEST.in
  README.md
  action.yaml
  docker-entrypoint.sh
  docker/.env
  docker/Dockerfile
  docker/docker-compose.yml
  pip_cli
  prj.conf
  samples/basic/CMakeLists.txt
  samples/basic/prj.conf
  samples/basic/src/main.c
  samples/basic/zeta.cmake
  samples/basic/zeta.yaml
  setup.py
  templates/zeta_callbacks.template.h
  templates/zeta_custom_functions.template.h
  templates/zeta_threads.template.c
  templates/zeta_threads.template.h
  test/include/zeta_unit_tests.h
  test/src/test_functions.c
  test/src/test_main.c
  test/zeta_test.yaml
  tests/CMakeLists.txt
  tests/include/zeta_unit_tests.h
  tests/prj.conf
  tests/src/test_functions.c
  tests/src/test_main.c
  tests/zeta.cmake
  tests/zeta.yaml
  zeta/__init__.py
  zeta/__main__.py
  zeta/_version.py
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta.template.h
  zeta/templates/zeta.template.yaml
  zeta/templates/zeta/CMakeLists.txt
  zeta/templates/zeta/Kconfig
  zeta/templates/zeta/include/.empty
  zeta/templates/zeta/src/.empty
  zeta/templates/zeta/zephyr/module.yml
  zeta/templates/zeta_callbacks.template.h
  zeta/templates/zeta_custom_functions.template.h
  zeta/templates/zeta_threads.template.c
  zeta/templates/zeta_threads.template.h
  zeta/zeta.py
  zeta_generate.py
Labels: enhancement

#16 Add documentation generation mechanism
  docs/Doxyfile
  docs/Makefile
  docs/requirements.txt
  docs/source/basics.rst
  docs/source/code.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/license.rst
Labels: documentation

#18 Improve Zeta-cli OO reusability and prints
  samples/basic/zeta.cmake
  tests/zeta.cmake
  zeta/_version.py
  zeta/templates/zeta.template.cmake
  zeta/templates/zeta/CMakeLists.txt
  zeta/zeta.py
Labels: enhancement

#19 Documentation/rtd
  docs/Makefile
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#22 Add PlantUML support to the documentation
  docs/source/basics.rst
  docs/source/conf.py
Labels: documentation, enhancement

#24 Add and improve doxygen comments in zeta.h/c
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
Labels: documentation

#25 Fix PlantUML dependencies
  docs/requirements.txt
Labels: bug, documentation

#26 Samples/light
  .gitignore
  samples/light_control/CMakeLists.txt
  samples/light_control/prj.conf
  samples/light_control/src/core.c
  samples/light_control/src/main.c
  samples/light_control/src/net.c
  samples/light_control/src/peripheral.c
  samples/light_control/zeta.cmake
  samples/light_control/zeta.yaml
Labels: samples

#27 Refactoring/c code
  samples/basic/src/main.c
  samples/light_control/src/core.c
  samples/light_control/src/net.c
  samples/light_control/src/peripheral.c
  tests/src/test_functions.c
  tests/src/test_main.c
  zeta-run-tests.sh
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
  zeta/zeta.py
Labels: refactoring

#33 Enhancement/remove name field services
  samples/basic/zeta.yaml
  samples/light_control/zeta.yaml
  tests/zeta.yaml
  zeta/templates/zeta.template.yaml
  zeta/zeta.py
Labels: enhancement

#39 Add zt_data_t and its handle methods
  tests/src/test_functions.c
  tests/src/test_main.c
  zeta/templates/zeta.template.c
  zeta/templates/zeta.template.h
Labels: feature
